alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias open="~/Dropbox/open.sh"
alias dm="docker-machine"
alias zshr="source ~/.zshrc"
alias sdocker="sudo docker"
alias vven="virtualenv"
alias sdig="dig +short"
alias frz="~/franz > /dev/null 2>&1 &"
alias bb="byobu"
